apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch : |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: lyzhang19999/vote:env
    target:
      kind: Deployment
      name: vote

helmCharts:
  - name: redis
    version: "17.16.0"
    repo: "https://charts.bitnami.com/bitnami"
    valuesInline:
      fullnameOverride: redis
      auth:
        enabled: false
  - name: postgresql-ha
    version: "11.9.0"
    repo: "https://charts.bitnami.com/bitnami"
    valuesInline:
      fullnameOverride: db
      global:
        postgressql:
          username: postgres
          password: postgres
          database: postgres
          repmgrUsername: postgres
          repmgrPassword: postgres
